project:
  type: website
  output-dir: docs

website:
  title: "GROWER-demo-site"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Temperature Graphs
        href: demo.qmd      
      - text: Example Images
        href: images.qmd

format:
  html:
    theme: Flatly
    dark: Darkly
    css: styles.css
    toc: true