project:
  type: website
  output-dir: docs

website:
  title: "GROWER-demo-site"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Example Images
        href: images.qmd
      - text: Smiley Graph
        href: demo.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



